### ISSUE TITLE
παραδοτεο 1/αποριες

### ISSUE THREAD

**Issue by ghost** [ioniodi/Super-Mario#32]
-οταν λετε να αλλαξουμε τον πρωταγωνιστη φτανει να μην εχει ιδια χρωματα η θελετε ολοκληρο animation?
-οταν λετε να προσθεσουμε επιπλεον αντικειμενα πχ ενα δεντρακι στο backround η κατι με μεγαλυτερη συμμετοχη στην ροη του παιχνιδιου?
-ποιο εργαλειο προτεινετε (tiled,unity)?(με το tiled δεν μπορω να κανω png tileset και βλεπω οτι εσεις το εχετε κανει υπαρχει λυση?)

**Comment by merkourisa** [comment]
Αν έχεις απορία για κάποιο από τα παραδοτέα τότε πρέπει να την υποβάλλεις στο αντίστοιχο issue του παραδοτέου και όχι να ανοίξεις νέο issue
